DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS income_category CASCADE;
DROP TABLE IF EXISTS expense_category CASCADE;
DROP TABLE IF EXISTS currency CASCADE;
DROP TABLE IF EXISTS income CASCADE;
DROP TABLE IF EXISTS expense CASCADE;
