// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"gopkg.in/nullbio/null.v6"
)

// Expense is an object representing the database table.
type Expense struct {
	ID         int          `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID     int          `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	CategoryID int          `boil:"category_id" json:"category_id" toml:"category_id" yaml:"category_id"`
	DateTime   time.Time    `boil:"date_time" json:"date_time" toml:"date_time" yaml:"date_time"`
	Title      string       `boil:"title" json:"title" toml:"title" yaml:"title"`
	Reference  null.String  `boil:"reference" json:"reference,omitempty" toml:"reference" yaml:"reference,omitempty"`
	Value      float64      `boil:"value" json:"value" toml:"value" yaml:"value"`
	CurrencyID int          `boil:"currency_id" json:"currency_id" toml:"currency_id" yaml:"currency_id"`
	Rate       null.Float64 `boil:"rate" json:"rate,omitempty" toml:"rate" yaml:"rate,omitempty"`

	R *expenseR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L expenseL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

// expenseR is where relationships are stored.
type expenseR struct {
	User     *User
	Category *ExpenseCategory
	Currency *Currency
}

// expenseL is where Load methods for each relationship are stored.
type expenseL struct{}

var (
	expenseColumns               = []string{"id", "user_id", "category_id", "date_time", "title", "reference", "value", "currency_id", "rate"}
	expenseColumnsWithoutDefault = []string{"user_id", "category_id", "date_time", "title", "reference", "value", "currency_id"}
	expenseColumnsWithDefault    = []string{"id", "rate"}
	expensePrimaryKeyColumns     = []string{"user_id", "category_id", "date_time", "title"}
)

type (
	// ExpenseSlice is an alias for a slice of pointers to Expense.
	// This should generally be used opposed to []Expense.
	ExpenseSlice []*Expense
	// ExpenseHook is the signature for custom Expense hook methods
	ExpenseHook func(boil.Executor, *Expense) error

	expenseQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	expenseType                 = reflect.TypeOf(&Expense{})
	expenseMapping              = queries.MakeStructMapping(expenseType)
	expensePrimaryKeyMapping, _ = queries.BindMapping(expenseType, expenseMapping, expensePrimaryKeyColumns)
	expenseInsertCacheMut       sync.RWMutex
	expenseInsertCache          = make(map[string]insertCache)
	expenseUpdateCacheMut       sync.RWMutex
	expenseUpdateCache          = make(map[string]updateCache)
	expenseUpsertCacheMut       sync.RWMutex
	expenseUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var expenseBeforeInsertHooks []ExpenseHook
var expenseBeforeUpdateHooks []ExpenseHook
var expenseBeforeDeleteHooks []ExpenseHook
var expenseBeforeUpsertHooks []ExpenseHook

var expenseAfterInsertHooks []ExpenseHook
var expenseAfterSelectHooks []ExpenseHook
var expenseAfterUpdateHooks []ExpenseHook
var expenseAfterDeleteHooks []ExpenseHook
var expenseAfterUpsertHooks []ExpenseHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Expense) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range expenseBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Expense) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range expenseBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Expense) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range expenseBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Expense) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range expenseBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Expense) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range expenseAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Expense) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range expenseAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Expense) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range expenseAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Expense) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range expenseAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Expense) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range expenseAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddExpenseHook registers your hook function for all future operations.
func AddExpenseHook(hookPoint boil.HookPoint, expenseHook ExpenseHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		expenseBeforeInsertHooks = append(expenseBeforeInsertHooks, expenseHook)
	case boil.BeforeUpdateHook:
		expenseBeforeUpdateHooks = append(expenseBeforeUpdateHooks, expenseHook)
	case boil.BeforeDeleteHook:
		expenseBeforeDeleteHooks = append(expenseBeforeDeleteHooks, expenseHook)
	case boil.BeforeUpsertHook:
		expenseBeforeUpsertHooks = append(expenseBeforeUpsertHooks, expenseHook)
	case boil.AfterInsertHook:
		expenseAfterInsertHooks = append(expenseAfterInsertHooks, expenseHook)
	case boil.AfterSelectHook:
		expenseAfterSelectHooks = append(expenseAfterSelectHooks, expenseHook)
	case boil.AfterUpdateHook:
		expenseAfterUpdateHooks = append(expenseAfterUpdateHooks, expenseHook)
	case boil.AfterDeleteHook:
		expenseAfterDeleteHooks = append(expenseAfterDeleteHooks, expenseHook)
	case boil.AfterUpsertHook:
		expenseAfterUpsertHooks = append(expenseAfterUpsertHooks, expenseHook)
	}
}

// OneP returns a single expense record from the query, and panics on error.
func (q expenseQuery) OneP() *Expense {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single expense record from the query.
func (q expenseQuery) One() (*Expense, error) {
	o := &Expense{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for expense")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Expense records from the query, and panics on error.
func (q expenseQuery) AllP() ExpenseSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Expense records from the query.
func (q expenseQuery) All() (ExpenseSlice, error) {
	var o []*Expense

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Expense slice")
	}

	if len(expenseAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Expense records in the query, and panics on error.
func (q expenseQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Expense records in the query.
func (q expenseQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count expense rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q expenseQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q expenseQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if expense exists")
	}

	return count > 0, nil
}

// UserG pointed to by the foreign key.
func (o *Expense) UserG(mods ...qm.QueryMod) userQuery {
	return o.User(boil.GetDB(), mods...)
}

// User pointed to by the foreign key.
func (o *Expense) User(exec boil.Executor, mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(exec, queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// CategoryG pointed to by the foreign key.
func (o *Expense) CategoryG(mods ...qm.QueryMod) expenseCategoryQuery {
	return o.Category(boil.GetDB(), mods...)
}

// Category pointed to by the foreign key.
func (o *Expense) Category(exec boil.Executor, mods ...qm.QueryMod) expenseCategoryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.CategoryID),
	}

	queryMods = append(queryMods, mods...)

	query := ExpenseCategories(exec, queryMods...)
	queries.SetFrom(query.Query, "\"expense_category\"")

	return query
}

// CurrencyG pointed to by the foreign key.
func (o *Expense) CurrencyG(mods ...qm.QueryMod) currencyQuery {
	return o.Currency(boil.GetDB(), mods...)
}

// Currency pointed to by the foreign key.
func (o *Expense) Currency(exec boil.Executor, mods ...qm.QueryMod) currencyQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.CurrencyID),
	}

	queryMods = append(queryMods, mods...)

	query := Currencies(exec, queryMods...)
	queries.SetFrom(query.Query, "\"currency\"")

	return query
} // LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (expenseL) LoadUser(e boil.Executor, singular bool, maybeExpense interface{}) error {
	var slice []*Expense
	var object *Expense

	count := 1
	if singular {
		object = maybeExpense.(*Expense)
	} else {
		slice = *maybeExpense.(*[]*Expense)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &expenseR{}
		}
		args[0] = object.UserID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &expenseR{}
			}
			args[i] = obj.UserID
		}
	}

	query := fmt.Sprintf(
		"select * from \"users\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}
	defer results.Close()

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if len(expenseAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.User = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				break
			}
		}
	}

	return nil
}

// LoadCategory allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (expenseL) LoadCategory(e boil.Executor, singular bool, maybeExpense interface{}) error {
	var slice []*Expense
	var object *Expense

	count := 1
	if singular {
		object = maybeExpense.(*Expense)
	} else {
		slice = *maybeExpense.(*[]*Expense)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &expenseR{}
		}
		args[0] = object.CategoryID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &expenseR{}
			}
			args[i] = obj.CategoryID
		}
	}

	query := fmt.Sprintf(
		"select * from \"expense_category\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ExpenseCategory")
	}
	defer results.Close()

	var resultSlice []*ExpenseCategory
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ExpenseCategory")
	}

	if len(expenseAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Category = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CategoryID == foreign.ID {
				local.R.Category = foreign
				break
			}
		}
	}

	return nil
}

// LoadCurrency allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (expenseL) LoadCurrency(e boil.Executor, singular bool, maybeExpense interface{}) error {
	var slice []*Expense
	var object *Expense

	count := 1
	if singular {
		object = maybeExpense.(*Expense)
	} else {
		slice = *maybeExpense.(*[]*Expense)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &expenseR{}
		}
		args[0] = object.CurrencyID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &expenseR{}
			}
			args[i] = obj.CurrencyID
		}
	}

	query := fmt.Sprintf(
		"select * from \"currency\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Currency")
	}
	defer results.Close()

	var resultSlice []*Currency
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Currency")
	}

	if len(expenseAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Currency = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CurrencyID == foreign.ID {
				local.R.Currency = foreign
				break
			}
		}
	}

	return nil
}

// SetUserG of the expense to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Expenses.
// Uses the global database handle.
func (o *Expense) SetUserG(insert bool, related *User) error {
	return o.SetUser(boil.GetDB(), insert, related)
}

// SetUserP of the expense to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Expenses.
// Panics on error.
func (o *Expense) SetUserP(exec boil.Executor, insert bool, related *User) {
	if err := o.SetUser(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUserGP of the expense to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Expenses.
// Uses the global database handle and panics on error.
func (o *Expense) SetUserGP(insert bool, related *User) {
	if err := o.SetUser(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetUser of the expense to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Expenses.
func (o *Expense) SetUser(exec boil.Executor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"expense\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, expensePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserID, o.CategoryID, o.DateTime, o.Title}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID

	if o.R == nil {
		o.R = &expenseR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			Expenses: ExpenseSlice{o},
		}
	} else {
		related.R.Expenses = append(related.R.Expenses, o)
	}

	return nil
}

// SetCategoryG of the expense to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.CategoryExpenses.
// Uses the global database handle.
func (o *Expense) SetCategoryG(insert bool, related *ExpenseCategory) error {
	return o.SetCategory(boil.GetDB(), insert, related)
}

// SetCategoryP of the expense to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.CategoryExpenses.
// Panics on error.
func (o *Expense) SetCategoryP(exec boil.Executor, insert bool, related *ExpenseCategory) {
	if err := o.SetCategory(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetCategoryGP of the expense to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.CategoryExpenses.
// Uses the global database handle and panics on error.
func (o *Expense) SetCategoryGP(insert bool, related *ExpenseCategory) {
	if err := o.SetCategory(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetCategory of the expense to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.CategoryExpenses.
func (o *Expense) SetCategory(exec boil.Executor, insert bool, related *ExpenseCategory) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"expense\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"category_id"}),
		strmangle.WhereClause("\"", "\"", 2, expensePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserID, o.CategoryID, o.DateTime, o.Title}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CategoryID = related.ID

	if o.R == nil {
		o.R = &expenseR{
			Category: related,
		}
	} else {
		o.R.Category = related
	}

	if related.R == nil {
		related.R = &expenseCategoryR{
			CategoryExpenses: ExpenseSlice{o},
		}
	} else {
		related.R.CategoryExpenses = append(related.R.CategoryExpenses, o)
	}

	return nil
}

// SetCurrencyG of the expense to the related item.
// Sets o.R.Currency to related.
// Adds o to related.R.Expenses.
// Uses the global database handle.
func (o *Expense) SetCurrencyG(insert bool, related *Currency) error {
	return o.SetCurrency(boil.GetDB(), insert, related)
}

// SetCurrencyP of the expense to the related item.
// Sets o.R.Currency to related.
// Adds o to related.R.Expenses.
// Panics on error.
func (o *Expense) SetCurrencyP(exec boil.Executor, insert bool, related *Currency) {
	if err := o.SetCurrency(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetCurrencyGP of the expense to the related item.
// Sets o.R.Currency to related.
// Adds o to related.R.Expenses.
// Uses the global database handle and panics on error.
func (o *Expense) SetCurrencyGP(insert bool, related *Currency) {
	if err := o.SetCurrency(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetCurrency of the expense to the related item.
// Sets o.R.Currency to related.
// Adds o to related.R.Expenses.
func (o *Expense) SetCurrency(exec boil.Executor, insert bool, related *Currency) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"expense\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"currency_id"}),
		strmangle.WhereClause("\"", "\"", 2, expensePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserID, o.CategoryID, o.DateTime, o.Title}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CurrencyID = related.ID

	if o.R == nil {
		o.R = &expenseR{
			Currency: related,
		}
	} else {
		o.R.Currency = related
	}

	if related.R == nil {
		related.R = &currencyR{
			Expenses: ExpenseSlice{o},
		}
	} else {
		related.R.Expenses = append(related.R.Expenses, o)
	}

	return nil
}

// ExpensesG retrieves all records.
func ExpensesG(mods ...qm.QueryMod) expenseQuery {
	return Expenses(boil.GetDB(), mods...)
}

// Expenses retrieves all the records using an executor.
func Expenses(exec boil.Executor, mods ...qm.QueryMod) expenseQuery {
	mods = append(mods, qm.From("\"expense\""))
	return expenseQuery{NewQuery(exec, mods...)}
}

// FindExpenseG retrieves a single record by ID.
func FindExpenseG(userID int, categoryID int, dateTime time.Time, title string, selectCols ...string) (*Expense, error) {
	return FindExpense(boil.GetDB(), userID, categoryID, dateTime, title, selectCols...)
}

// FindExpenseGP retrieves a single record by ID, and panics on error.
func FindExpenseGP(userID int, categoryID int, dateTime time.Time, title string, selectCols ...string) *Expense {
	retobj, err := FindExpense(boil.GetDB(), userID, categoryID, dateTime, title, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindExpense retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindExpense(exec boil.Executor, userID int, categoryID int, dateTime time.Time, title string, selectCols ...string) (*Expense, error) {
	expenseObj := &Expense{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"expense\" where \"user_id\"=$1 AND \"category_id\"=$2 AND \"date_time\"=$3 AND \"title\"=$4", sel,
	)

	q := queries.Raw(exec, query, userID, categoryID, dateTime, title)

	err := q.Bind(expenseObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from expense")
	}

	return expenseObj, nil
}

// FindExpenseP retrieves a single record by ID with an executor, and panics on error.
func FindExpenseP(exec boil.Executor, userID int, categoryID int, dateTime time.Time, title string, selectCols ...string) *Expense {
	retobj, err := FindExpense(exec, userID, categoryID, dateTime, title, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Expense) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Expense) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Expense) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Expense) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no expense provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(expenseColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	expenseInsertCacheMut.RLock()
	cache, cached := expenseInsertCache[key]
	expenseInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			expenseColumns,
			expenseColumnsWithDefault,
			expenseColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(expenseType, expenseMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(expenseType, expenseMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"expense\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"expense\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into expense")
	}

	if !cached {
		expenseInsertCacheMut.Lock()
		expenseInsertCache[key] = cache
		expenseInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Expense record. See Update for
// whitelist behavior description.
func (o *Expense) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Expense record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Expense) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Expense, and panics on error.
// See Update for whitelist behavior description.
func (o *Expense) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Expense.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Expense) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	expenseUpdateCacheMut.RLock()
	cache, cached := expenseUpdateCache[key]
	expenseUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			expenseColumns,
			expensePrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update expense, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"expense\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, expensePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(expenseType, expenseMapping, append(wl, expensePrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update expense row")
	}

	if !cached {
		expenseUpdateCacheMut.Lock()
		expenseUpdateCache[key] = cache
		expenseUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q expenseQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q expenseQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for expense")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ExpenseSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o ExpenseSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o ExpenseSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ExpenseSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), expensePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"expense\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, expensePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in expense slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Expense) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Expense) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Expense) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Expense) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no expense provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(expenseColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	expenseUpsertCacheMut.RLock()
	cache, cached := expenseUpsertCache[key]
	expenseUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			expenseColumns,
			expenseColumnsWithDefault,
			expenseColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			expenseColumns,
			expensePrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert expense, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(expensePrimaryKeyColumns))
			copy(conflict, expensePrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"expense\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(expenseType, expenseMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(expenseType, expenseMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert expense")
	}

	if !cached {
		expenseUpsertCacheMut.Lock()
		expenseUpsertCache[key] = cache
		expenseUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Expense record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Expense) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Expense record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Expense) DeleteG() error {
	if o == nil {
		return errors.New("models: no Expense provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Expense record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Expense) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Expense record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Expense) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Expense provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), expensePrimaryKeyMapping)
	sql := "DELETE FROM \"expense\" WHERE \"user_id\"=$1 AND \"category_id\"=$2 AND \"date_time\"=$3 AND \"title\"=$4"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from expense")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q expenseQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q expenseQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no expenseQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from expense")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o ExpenseSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o ExpenseSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Expense slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o ExpenseSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ExpenseSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Expense slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(expenseBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), expensePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"expense\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, expensePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from expense slice")
	}

	if len(expenseAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Expense) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Expense) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Expense) ReloadG() error {
	if o == nil {
		return errors.New("models: no Expense provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Expense) Reload(exec boil.Executor) error {
	ret, err := FindExpense(exec, o.UserID, o.CategoryID, o.DateTime, o.Title)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *ExpenseSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *ExpenseSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ExpenseSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty ExpenseSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ExpenseSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	expenses := ExpenseSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), expensePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"expense\".* FROM \"expense\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, expensePrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&expenses)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ExpenseSlice")
	}

	*o = expenses

	return nil
}

// ExpenseExists checks if the Expense row exists.
func ExpenseExists(exec boil.Executor, userID int, categoryID int, dateTime time.Time, title string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"expense\" where \"user_id\"=$1 AND \"category_id\"=$2 AND \"date_time\"=$3 AND \"title\"=$4 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, userID, categoryID, dateTime, title)
	}

	row := exec.QueryRow(sql, userID, categoryID, dateTime, title)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if expense exists")
	}

	return exists, nil
}

// ExpenseExistsG checks if the Expense row exists.
func ExpenseExistsG(userID int, categoryID int, dateTime time.Time, title string) (bool, error) {
	return ExpenseExists(boil.GetDB(), userID, categoryID, dateTime, title)
}

// ExpenseExistsGP checks if the Expense row exists. Panics on error.
func ExpenseExistsGP(userID int, categoryID int, dateTime time.Time, title string) bool {
	e, err := ExpenseExists(boil.GetDB(), userID, categoryID, dateTime, title)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ExpenseExistsP checks if the Expense row exists. Panics on error.
func ExpenseExistsP(exec boil.Executor, userID int, categoryID int, dateTime time.Time, title string) bool {
	e, err := ExpenseExists(exec, userID, categoryID, dateTime, title)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
